#!/bin/sh

set -e

version="$1"

KERNEL=vmlinuz-$version
INITRD=initrd.img-$version
UINITRD=u$INITRD

mkimage -A arm -T ramdisk -C none -d /boot/$INITRD /boot/$UINITRD
sed -i -e "/^kernel=/d" -e '1i\' -e "kernel=$KERNEL" -e "/^uinitrd=/d" -e '1i\' -e "uinitrd=$UINITRD" /boot/bootEnv.txt
